routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/admin', 'Admin\LoginController@showlogin')->name('login1');
Route::get('/admin/login', 'Admin\LoginController@showlogin')->name('login2');
Route::group(['namespace' => 'Admin','as' => 'admin.','prefix'=>'admin','middleware' => 'auth'], function () {
	Route::get('/dashboard', 'DashboardController@index')->name('home');

	Route::group(['as' => 'role.','prefix'=>'role'], function () {
		Route::get('/', 'RoleController@index')->name('list');
		Route::post('/datatable', 'RoleController@datatable')->name('data');
		Route::get('/add', 'RoleController@create')->name('add');
		Route::post('/store', 'RoleController@store')->name('store');
		Route::post('/destroy', 'RoleController@destroy')->name('destroy');
		Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('/update/{id}', 'RoleController@update')->name('update');
	});
	Route::group(['as' => 'permission.','prefix'=>'permission'], function () {
		Route::get('/', 'PermissionController@index')->name('list');
		Route::post('/datatable', 'PermissionController@datatable')->name('data');
		Route::get('/add', 'PermissionController@create')->name('add');
		Route::post('/store', 'PermissionController@store')->name('store');
		Route::get('/edit/{id}', 'PermissionController@edit')->name('edit');
		Route::post('/update/{id}', 'PermissionController@update')->name('update');
	});

	Route::group(['as' => 'users.','prefix' => 'users'], function () {
	    Route::get('/', 'UserController@index')->name('list');
	    Route::post('/datatable', 'UserController@datatable')->name('data');
	    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
		Route::post('/update/{id}', 'UserController@update')->name('update');
		Route::post('/changestatus', 'UserController@changestatus')->name('changestatus');
	});

	Route::group(['as' => 'contests.','prefix' => 'contests'], function () {
	    Route::get('/', 'ContestController@index')->name('list');
	    Route::post('/datatable', 'ContestController@datatable')->name('data');
	    Route::get('/add', 'ContestController@create')->name('add');
	    Route::post('/store', 'ContestController@store')->name('store');
	    Route::get('/edit/{id}', 'ContestController@edit')->name('edit');
		Route::post('/update/{id}', 'ContestController@update')->name('update');
		Route::post('/hastags', 'ContestController@hastags')->name('hastags');
		Route::post('/destroy', 'ContestController@destroy')->name('destroy');
	});
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Auth;
use DataTables;
use DB;

class RoleController extends Controller{
    
    public function index(Request $request){
        return view('admin.roles.index');
    }

    public function datatable(Request $request){
    	$roles = Role::orderBy('id','DESC');
    	return DataTables::of($roles)->addColumn('action', function($roles) {
            $edit_link="";
            $delete_link="";
            if(Auth::user()->can('edit-roles')){
                $edit_link = '<a href="'.route('admin.role.edit',$roles->id).'" data-toggle="tooltip" data-original-title="Edit"><i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>';
            }
            if(Auth::user()->can('delete-roles')){
                $delete_link = '<a href="javascript:void(0);" onclick="delete_confirmation(this,'.$roles->id.')" data-toggle="tooltip" data-original-title="Delete"><i class="fas fa-window-close text-danger"></i> </a>';
            }
            return $edit_link.$delete_link;
        })->make(true);
    }

    public function create(){
        $permission = Permission::get();
        return view('admin.roles.create',compact('permission'));
    }

    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
        $role = Role::create(['name' => $request->input('name'),'description' => $request->input('name'),'page_permission'=>$request->input('name')]);
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('admin.role.list')->with('success','Role created successfully');
    }

    public function edit($id){
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
        return view('admin.roles.edit',compact('role','permission','rolePermissions'));
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('admin.role.list')->with('success','Role updated successfully');
    }

    public function destroy(Request $request){
        Role::where('id',$request->id)->delete();
        return response()->json(['succsess'=>true]);
    }

}

resources/views/admin/roles/create.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop Role
@endsection
@section('content')
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Add Role</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.role.list')}}">Role</a></li>
                <li class="breadcrumb-item active">Add Role</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="floating-labels m-t-40" method="post" action="{{route('admin.role.store')}}">
                        @csrf
                        <div class="form-group m-b-40">
                            <input type="text" class="form-control" id="input5" name="name" data-toggle="tooltip" data-placement="bottom" title="Name">
                            <span class="bar"></span>
                            <label for="input5">Name</label>
                        </div>
                        <div class="form-group m-b-40">
                            <div class="demo-checkbox">
                                <strong>Permission</strong><br/>
                                @php $i=1; @endphp
                                @foreach($permission as $value)
                                    <input type="checkbox" id="md_checkbox_{{$value->id}}" name="permission[]" class="chk-col-indigo" value="{{$value->id}}" />
                                    <label for="md_checkbox_{{$value->id}}">{{$value->display_name}}</label>
                                    @if($i%4==0)
                                    <br>
                                    @endif
                                    @php $i++; @endphp
                                @endforeach
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <button type="submit" class="btn btn-info waves-effect waves-light m-t-10"> <i class="fa fa-check"></i> Submit</button>
                                            <a href="{{route('admin.role.list')}}" class="btn btn-inverse m-t-10">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop Role
@endsection
@section('content')
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Edit Role</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.role.list')}}">Role</a></li>
                <li class="breadcrumb-item active">Edit Role</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="floating-labels m-t-40" method="post" action="{{route('admin.role.update',$role->id)}}">
                        @csrf
                        <div class="form-group m-b-40">
                            <input type="text" class="form-control" id="input5" name="name" data-toggle="tooltip" data-placement="bottom" title="Name" value="{{$role->name}}">
                            <span class="bar"></span>
                            <label for="input5">Name</label>
                        </div>
                        <div class="form-group m-b-40">
                            <div class="demo-checkbox">
                                <strong>Permission</strong><br/>
                                @php $i=1; @endphp
                                @foreach($permission as $value)
                                    @if(in_array($value->id,$rolePermissions))
                                        @php
                                            $checkCheckbox='checked';
                                        @endphp
                                    @else
                                        @php
                                            $checkCheckbox='';
                                        @endphp
                                    @endif
                                        <input type="checkbox" id="md_checkbox_{{$value->id}}" name="permission[]" class="chk-col-indigo" value="{{$value->id}}" {{ $checkCheckbox ?? ''}} />
                                        <label for="md_checkbox_{{$value->id}}">{{$value->display_name}}</label>
                                        @if($i%4==0)
                                            <br>
                                        @endif
                                    @php $i++; @endphp
                                @endforeach
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <button type="submit" class="btn btn-info waves-effect waves-light m-t-10"> <i class="fa fa-check"></i> Submit</button>
                                            <a href="{{route('admin.role.list')}}" class="btn btn-inverse m-t-10">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop Role
@endsection
@section('content')
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Role List</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">Role List</li>
            </ol>
        </div>
        <div class="col-md-7 col-4 align-self-center">
            <div class="d-flex m-t-10 justify-content-end">
                <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                    @if(Auth::user()->can('add-roles'))
                        <a href="{{route('admin.role.add')}}" class="btn btn-info waves-effect waves-light m-t-10 add-a-tag-color">Add Role</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <!-- Column -->
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table striped m-b-20" id="editable-datatable">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    @if(Auth::user()->can('edit-roles') || Auth::user()->can('delete-roles'))
                                    @php
                                        $is_role=true;
                                    @endphp
                                    <th>Action</th>
                                    @else
                                    @php
                                        $is_role=false;
                                    @endphp
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{asset('assets/plugins/jquery-datatables-editable/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/plugins/datatables/media/js/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/mindmup-editabletable.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/numeric-input-example.js')}}"></script>
@if(Session::has('success'))
    <script type="text/javascript">
        const Toast = Swal.mixin({
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 3000
        });
        Toast.fire({
          type: 'success',
          title: '{!! Session::get("success") !!}'
        });
    </script>
@endif
<script type="text/javascript">
    $(function() {
        var role = '{{$is_role}}';
        var table=$('#editable-datatable').DataTable({
           processing: true,
           serverSide: true,
           ajax:{
                headers: {'X-CSRF-Token': Laravel.csrfToken},
                url:'{!! route("admin.role.data") !!}',
                type:'POST'
            },
           columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'action', name: 'action',visible : role }
            ]
        });
    });
    function delete_confirmation(ele,id){
        swal({   
            title: "Are you sure?",   
            text: "You won't be able to revert this!",   
            type: "warning",   
            showCancelButton: true,   
            confirmButtonColor: "#DD6B55",   
            confirmButtonText: "Yes, delete it!",   
            closeOnConfirm: false,
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    headers: {'X-CSRF-Token': Laravel.csrfToken},
                    url: '{{ route("admin.role.destroy") }}',
                    dataType : 'json',
                    data: {id:id},
                    success: function(response) {
                        if(response.succsess == true){
                            Swal.fire(
                              'Deleted!',
                              'Your file has been deleted.',
                              'success'
                            );
                            $('#editable-datatable').DataTable().ajax.reload();
                            redrawDatatable();
                        }
                    },
                    error: function (jqXHR, status, exception) {
                        if (jqXHR.status === 0) {
                            error = 'Not connected.\nPlease verify your network connection.';
                        } else if (jqXHR.status == 404) {
                            error = 'The requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            error = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            error = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            error = 'Time out error.';
                        } else if (exception === 'abort') {
                            error = 'Ajax request aborted.';
                        } else {
                            error = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        Swal.fire('Error!',error,'error');
                    }
                });
            }
        });
    }
    function redrawDatatable(){
        $('#editable-datatable').DataTable().ajax.reload();
    }
</script>
@endsection