routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/admin', 'Admin\LoginController@showlogin')->name('login1');
Route::get('/admin/login', 'Admin\LoginController@showlogin')->name('login2');
Route::group(['namespace' => 'Admin','as' => 'admin.','prefix'=>'admin','middleware' => 'auth'], function () {
	Route::get('/dashboard', 'DashboardController@index')->name('home');

	Route::group(['as' => 'role.','prefix'=>'role'], function () {
		Route::get('/', 'RoleController@index')->name('list');
		Route::post('/datatable', 'RoleController@datatable')->name('data');
		Route::get('/add', 'RoleController@create')->name('add');
		Route::post('/store', 'RoleController@store')->name('store');
		Route::post('/destroy', 'RoleController@destroy')->name('destroy');
		Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('/update/{id}', 'RoleController@update')->name('update');
	});
	Route::group(['as' => 'permission.','prefix'=>'permission'], function () {
		Route::get('/', 'PermissionController@index')->name('list');
		Route::post('/datatable', 'PermissionController@datatable')->name('data');
		Route::get('/add', 'PermissionController@create')->name('add');
		Route::post('/store', 'PermissionController@store')->name('store');
		Route::get('/edit/{id}', 'PermissionController@edit')->name('edit');
		Route::post('/update/{id}', 'PermissionController@update')->name('update');
	});

	Route::group(['as' => 'users.','prefix' => 'users'], function () {
	    Route::get('/', 'UserController@index')->name('list');
	    Route::post('/datatable', 'UserController@datatable')->name('data');
	    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
		Route::post('/update/{id}', 'UserController@update')->name('update');
		Route::post('/changestatus', 'UserController@changestatus')->name('changestatus');
	});

	Route::group(['as' => 'contests.','prefix' => 'contests'], function () {
	    Route::get('/', 'ContestController@index')->name('list');
	    Route::post('/datatable', 'ContestController@datatable')->name('data');
	    Route::get('/add', 'ContestController@create')->name('add');
	    Route::post('/store', 'ContestController@store')->name('store');
	    Route::get('/edit/{id}', 'ContestController@edit')->name('edit');
		Route::post('/update/{id}', 'ContestController@update')->name('update');
		Route::post('/hastags', 'ContestController@hastags')->name('hastags');
		Route::post('/destroy', 'ContestController@destroy')->name('destroy');
	});
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens,Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'FirstName', 'LastName', 'email', 'password' ,'Age' ,'Gender' ,'Upi' ,'ProfilePic','remember_token','created_at','updated_at','ProfileVid','MobileNumber','BirthDate','WorkAt','Relationship','Hobbies','Address','Status','Biodata','EmailVerificationToken','Roles'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function FreeContest(){
        return $this->hasMany('App\Contest', 'UserId', 'id')->where([['IsPaid','=', 0],['IsActive','=',1]]);
    }

    public function PaidContest(){
        return $this->hasMany('App\Contest', 'UserId', 'id')->where([['IsPaid','=', 1],['IsActive','=',1]]);   
    }

    public function role(){
        return $this->hasOne(Role::class,'id','Roles');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\User;
use DB;
use Validator;
use DataTables;

class UserController extends Controller{

    public function index(Request $request){
        return view('admin.users.index');
    }

    public function datatable(Request $request){
        $user = User::select(['id','Roles',DB::raw("CONCAT(users.FirstName,' ',users.LastName) as fullname"),'email','IsActive','created_at'])->with('role');
        return Datatables::eloquent($user)
            ->addColumn('action', function($user) {
                $edit_link = '<a href="'.route('admin.users.edit',$user->id).'" data-toggle="tooltip" data-original-title="Edit"><i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>';
                return $edit_link;
            })
            ->addColumn('role', function (User $user) {
                return $user->role->name;
            })
            ->addColumn('IsActive', function($user) {
                if($user->IsActive == 0){
                    return '<a href="javascript:void(0);" class="btn btn-danger" data-title="Active" onclick="changestatus(this,'.$user->id.',1);">InActive</a>';
                }else{
                    return '<a href="javascript:void(0);" class="btn btn-success" data-title="InActive" onclick="changestatus(this,'.$user->id.',0);">Active</a>';
                }
            })
            ->editColumn('created_at', function($user) {
                return date('d-m-Y', strtotime($user->created_at));
            })
            ->filterColumn('fullname', function($query, $keyword) {
                $sql = "CONCAT(users.FirstName,'-',users.LastName)  like ?";
                $query->whereRaw($sql, ["%{$keyword}%"]);
            })
            ->filterColumn('IsActive', function ($query, $keyword) {
                if (strstr(strtolower("active"), strtolower($keyword) ) !== false) {
                    $query->whereRaw("IsActive = 1");
                }elseif (strstr(strtolower("inactive"), strtolower($keyword) ) !== false) {
                    $query->whereRaw("IsActive = 0");
                }
            })
            ->filterColumn('created_at', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(created_at,'%d-%m-%Y') like ?", ["%$keyword%"]);
            })
            ->rawColumns(['IsActive','action'])
            ->make(true);
    }

    public function edit($id){
        $user = User::where('id',$id)->first();
        if($user){
            $roles = Role::all();
            return view('admin.users.edit', compact('user','roles'));
        }else{
            return abort(404); 
        }
    }

    public function update(Request $request, $id){
        $validator = Validator::make($request->all(), [
            'role' => 'required',
            'FirstName' => 'required',
            'LastName' => 'required',
            'email' => 'required|max:255'
        ]);
        if ($validator->fails()) {
            return redirect()->route('admin.users.edit',$id)->withErrors($validator)->withInput();
        }
        $role = Role::findById($request->role);
        $user = User::where('id',$id)->first();
        $user->FirstName        = $request->FirstName;
        $user->LastName         = $request->LastName;
        $user->email            = $request->email;
        $user->Age              = $request->Age;
        $user->Gender           = $request->Gender;
        $user->syncRoles($role->name);
        $user->save();
        return redirect()->route('admin.users.list')->with('success','User updated successfully');
    }

    public function changestatus(Request $request) {
        $response['success'] = false;
        if ($request->ajax()) {
            try {
                User::where('id',$request->id)->update(['IsActive'=>$request->status]);
                $response['success'] = true;
            } catch (Exception $e) {
                $response['success'] = false;
            }
        }
        return response()->json($response);
    }

}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Carbon\Carbon;
use App\User;
use Str;

class UserController extends Controller
{
    public function GetUserProfile(Request $request)
    {
       	if($request->UserProfileId>0)
    	{
    		$userProfileData=User::where('id',$request->UserProfileId)->first();
    	}
    	else{
    		$userProfileData=$request->user();
    	}
    	if ($userProfileData) {
    	return response()->json([
                'Success'=>true,
                'user_data'=>$userProfileData,
                'message' => 'Success.'
            ], 201);
    	 }
    	 else{
    	 	return response()->json([
                'Success'=>false,
                'message' => 'User Not Found.'
            ], 401);
    	 }
    }
    public function EditProfile(Request $request)
    {
    	$userProfileData=$request->user();
    	if($userProfileData->email!=$request->Email)
    	{
    		$unique_validation='|unique:users';
    	}
    	else{
    		$unique_validation="";
    	}
    	$request->validate([
            'FirstName' => 'required|string',
            'LastName' => 'required|string',
            'Email' => 'required|string|email'.$unique_validation.'',
            'ProfilePic' => 'image|max:10000|mimes:jpeg,png,jpg,gif,svg',
            'ProfileVideo' => 'mimetypes:video/avi,video/mpeg,video/mp4,video/mp3,video/quicktime',
            'DOB'=>['before:5 years ago']
        ]);
    	$ImageFileName=$userProfileData->profile_pic;
        if($request->hasFile('ProfileImage'))
        {
        	$ProfilePic = $request->file('ProfileImage');
        	$ImageFileName = time().$ProfilePic->getClientOriginalName();
        	$ProfilePic->move(public_path().'/uploads/ProfilePic/', $ImageFileName);
        }
        $VideoFileName=$userProfileData->profile_vid;
        if($request->hasFile('ProfileVideo'))
        {
        	$ProfileVideo = $request->file('ProfileVideo');
        	$VideoFileName = time().$ProfileVideo->getClientOriginalName();
        	$ProfileVideo->move(public_path().'/uploads/ProfileVideo/', $VideoFileName);
        }

        user::where('id', $userProfileData->id)->update(['ProfilePic'=>$ImageFileName,'ProfileVid'=>$VideoFileName,'LastName'=>$request->LastName,'FirstName' => $request->FirstName,'BirthDate'=>date('Y-m-d',strtotime($request->DOB)),'email'=>$request->Email,'WorkAt'=>$request->WorkAt,'Relationship'=>$request->Relationship,'Hobbies'=>$request->Hobbies,'Address'=>$request->Address,'MobileNumber'=>$request->MobileNo,'Status'=>$request->Status,'Biodata'=>$request->Bio]);
        return response()->json([
                'Success'=>true,
                'message' => 'Profile updated successfully.'
            ], 201);
         


    }

}

resources/views/admin/users/edit.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop User
@endsection
@section('content')
<style type="text/css">
    .invalid-feedback{
        display: block;
        font-weight: bold;
    }
</style>
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Edit User</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.users.list')}}">User</a></li>
                <li class="breadcrumb-item active">Edit User</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="floating-labels m-t-40" method="post" action="{{ route('admin.users.update', $user->id) }}">
                        @csrf
                        <div class="form-group m-b-40">
                            <select class="form-control p-0" name="role" id="role">
                                <option value="">Please select user role</option>
                                @foreach($roles as $role)
                                    <option {{ ($role->id == $user->roles->first()->id)?'selected':'' }} value="{{ $role->id }}"> {{ $role->name }}</option>
                                @endforeach
                            </select>
                            <span class="bar"></span>
                            <label for="role">Role</label>
                            @error('role')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('role') }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="FirstName" id="FirstName" value="{{ ($user->FirstName)? $user->FirstName : old('FirstName') }}" data-toggle="tooltip" data-placement="bottom" title="First Name">
                                <span class="bar"></span>
                                <label for="FirstName">First Name</label>
                                @error('FirstName')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('FirstName') }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="LastName" id="LastName" value="{{ ($user->LastName)? $user->LastName : old('LastName') }}" data-toggle="tooltip" data-placement="bottom" title="Last Name">
                                <span class="bar"></span>
                                <label for="LastName">Last Name</label>
                                @error('LastName')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('LastName') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="email" id="email" value="{{ ($user->email)? $user->email : old('email') }}" data-toggle="tooltip" data-placement="bottom" title="Email">
                                <span class="bar"></span>
                                <label for="email">Email</label>
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <input type="number" class="form-control" name="Age" id="Age" value="{{ ($user->Age)? $user->Age : old('Age') }}" data-toggle="tooltip" data-placement="bottom" title="Age" min="1" max="150">
                                <span class="bar"></span>
                                <label for="Age">Age</label>
                                @error('Age')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('Age') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <select class="form-control p-0" name="Gender" id="Gender">
                                    <option value="">Please select gender</option>
                                    <option value="Male" {{ (old('Gender', $user->Gender)=='Male')?'selected':'' }} >Male</option>
                                    <option value="Female" {{ (old('Gender', $user->Gender)=='Female')?'selected':'' }} >Female</option>
                                </select>
                                <span class="bar"></span>
                                <label for="Gender">Gender</label>
                                @error('Gender')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('Gender') }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <button type="submit" class="btn btn-info waves-effect waves-light m-t-10"> <i class="fa fa-check"></i> Submit</button>
                                            <a href="{{route('admin.users.list')}}" class="btn btn-inverse m-t-10">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop User
@endsection

@section('content')
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">User List</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">User List</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <!-- Column -->
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table striped m-b-20" id="DataTable1">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Role</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{asset('assets/plugins/jquery-datatables-editable/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/plugins/datatables/media/js/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/mindmup-editabletable.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/numeric-input-example.js')}}"></script>
@if(Session::has('success'))
<script type="text/javascript">
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
    });
    Toast.fire({
        type: 'success',
        title: '{!! Session::get("success") !!}'
    });
</script>
@endif
<script>
    $(function() {
        var table=$('#DataTable1').DataTable({
            processing: true,
            serverSide: true,
            aoColumnDefs: [{ "bSortable": false, "aTargets": [6] }],
            ajax:{
                headers: {'X-CSRF-Token': Laravel.csrfToken},
                url:'{!! route("admin.users.data") !!}',
                type:'POST'
            },
            columns: [
                {data: 'id',name: 'id'},
                {data: 'role',name: 'role.name'},
                {data: 'fullname',name: 'fullname'},
                {data: 'email',name: 'email'},
                {data: 'IsActive', name: 'IsActive'},
                {data: 'created_at',name: 'created_at'},
                {data: 'action',name: 'action'}
            ],
            order: [[0, 'desc']]
        });
    });
    function capitalizeFirstLetter(string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    function changestatus(ele,id,status){
        var error;
        Swal.fire({
            title: 'Are you sure to '+$(ele).data("title")+' this user ?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, '+capitalizeFirstLetter($(ele).data("title"))+' it!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    headers: {'X-CSRF-Token': Laravel.csrfToken},
                    url: '{{ route("admin.users.changestatus") }}',
                    dataType : 'json',
                    data: {id:id,status:status},
                    success: function(response) {
                        if(response.success == true){
                            Swal.fire(capitalizeFirstLetter($(ele).data("title"))+'ed!','User has been '+$(ele).data("title")+'.','success');
                            if(status=='0'){
                                $(ele).attr('onclick','changestatus(this,'+id+',1);');
                                $(ele).attr('class','btn btn-danger');
                                $(ele).data('title','Active');
                                $(ele).html('InActive');
                            }else{
                                $(ele).attr('onclick','changestatus(this,'+id+',0);');
                                $(ele).attr('class','btn btn-success');
                                $(ele).data('title','InActive');
                                $(ele).html('Active');
                            }
                        }
                    },
                    error: function (jqXHR, status, exception) {
                        if (jqXHR.status === 0) {
                            error = 'Not connected.\nPlease verify your network connection.';
                        } else if (jqXHR.status == 404) {
                            error = 'The requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            error = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            error = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            error = 'Time out error.';
                        } else if (exception === 'abort') {
                            error = 'Ajax request aborted.';
                        } else {
                            error = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        Swal.fire('Error!',error,'error');
                    }
                });
            }
        });
    }
    </script>
@endsection