routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/admin', 'Admin\LoginController@showlogin')->name('login1');
Route::get('/admin/login', 'Admin\LoginController@showlogin')->name('login2');
Route::group(['namespace' => 'Admin','as' => 'admin.','prefix'=>'admin','middleware' => 'auth'], function () {
	Route::get('/dashboard', 'DashboardController@index')->name('home');

	Route::group(['as' => 'role.','prefix'=>'role'], function () {
		Route::get('/', 'RoleController@index')->name('list');
		Route::post('/datatable', 'RoleController@datatable')->name('data');
		Route::get('/add', 'RoleController@create')->name('add');
		Route::post('/store', 'RoleController@store')->name('store');
		Route::post('/destroy', 'RoleController@destroy')->name('destroy');
		Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('/update/{id}', 'RoleController@update')->name('update');
	});
	Route::group(['as' => 'permission.','prefix'=>'permission'], function () {
		Route::get('/', 'PermissionController@index')->name('list');
		Route::post('/datatable', 'PermissionController@datatable')->name('data');
		Route::get('/add', 'PermissionController@create')->name('add');
		Route::post('/store', 'PermissionController@store')->name('store');
		Route::get('/edit/{id}', 'PermissionController@edit')->name('edit');
		Route::post('/update/{id}', 'PermissionController@update')->name('update');
	});

	Route::group(['as' => 'users.','prefix' => 'users'], function () {
	    Route::get('/', 'UserController@index')->name('list');
	    Route::post('/datatable', 'UserController@datatable')->name('data');
	    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
		Route::post('/update/{id}', 'UserController@update')->name('update');
		Route::post('/changestatus', 'UserController@changestatus')->name('changestatus');
	});

	Route::group(['as' => 'contests.','prefix' => 'contests'], function () {
	    Route::get('/', 'ContestController@index')->name('list');
	    Route::post('/datatable', 'ContestController@datatable')->name('data');
	    Route::get('/add', 'ContestController@create')->name('add');
	    Route::post('/store', 'ContestController@store')->name('store');
	    Route::get('/edit/{id}', 'ContestController@edit')->name('edit');
		Route::post('/update/{id}', 'ContestController@update')->name('update');
		Route::post('/hastags', 'ContestController@hastags')->name('hastags');
		Route::post('/destroy', 'ContestController@destroy')->name('destroy');
	});
});

app/Contest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contest extends Model
{
	protected $table='contests';
    protected $fillable = [
        'UserId', 'ContestType', 'ContestTitle', 'StartTime' ,'EndTime' ,'RewardType' ,'GuestRewardPoints' ,'PremiumRewardPoints','ContestReffrenceImageUrl','IsActive','IsPaid','created_at','updated_at'
    ];
    public function ContestUser()
    {
    	return $this->hasMany('App\ContestUser','ContestId','Id');
    }
}

app/Http/Controllers/Admin/ContestController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Contest;
use App\Hashtags;
use App\ContestHashTag;
use Auth;
use DB;
use Validator;
use DataTables;
use Redirect;

class ContestController extends Controller
{
    public function index(Request $request){
        return view('admin.contests.index');
    }
    public function datatable(Request $request){
    	$contest = Contest::withCount('ContestUser')->orderBy('Id','DESC')->get();
    	
    	return DataTables::of($contest)->addColumn('action', function($contest) {
            $edit_link="";
            $delete_link="";
            if(Auth::user()->can('edit-contests')){
                $edit_link = '<a href="'.route('admin.contests.edit',$contest->Id).'" data-toggle="tooltip" data-original-title="Edit"><i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>';
            }
            if(Auth::user()->can('delete-contests')){
                $delete_link = '<a href="javascript:void(0);" onclick="delete_confirmation(this,'.$contest->Id.')" data-toggle="tooltip" data-original-title="Delete"><i class="fas fa-window-close text-danger"></i> </a>';
            }
            return $edit_link.$delete_link;
        })->make(true);
    }
    public function create(){
        return view('admin.contests.create');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'ContestReffrenceImageUrl' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'ContestType'=>'required',
            'ContestTitle'=>'required',
            'RewardType'=>'required',
            'RewardPoints'=>'required|numeric',
            'PremiumRewardPoints'=>'required|numeric',
            'StartTime'=>'required',
        ]);

        if($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }
        $FileName = '';
        if($request->hasFile('ContestReffrenceImageUrl'))
        {
            $ProfilePic = $request->file('ContestReffrenceImageUrl');
            $FileName = time().$ProfilePic->getClientOriginalName();
            $ProfilePic->move(public_path().'/uploads/ContestReffrenceImage/', $FileName);
        }
        if($request->IsPaid=='on')
        {
            $IsPaid='1';
        }
        else{
            $IsPaid='0';
        }
        $explode_duration=explode(' - ', $request->StartTime);
        $ContestData = Contest::create([
            'ContestType' => $request->ContestType,
            'UserId'=>'1',
            'ContestTitle' => $request->ContestTitle,
            'RewardType' => $request->RewardType,
            'GuestRewardPoints' => $request->RewardPoints,
            'PremiumRewardPoints' => $request->PremiumRewardPoints,
            'ContestReffrenceImageUrl' => $FileName,
            'IsActive' => '1',
            'StartTime'=>date('Y-m-d H:i:s',strtotime($explode_duration[0])),
            'EndTime'=>date('Y-m-d H:i:s',strtotime($explode_duration[1])),
            'IsPaid' => $IsPaid
        ]);
        $ContestId=$ContestData->id;
        if(!empty($request->has_tags))
        {
            foreach($request->has_tags as $has_tags_val)
            {
                if(is_numeric($has_tags_val))
                {
                    ContestHashTag::create([
                        'ContestID'=>$ContestId,
                        'HashTagID'=>$has_tags_val
                        ]);
                }
                else{
                    $hashTagData=Hashtags::create([
                        'HashTagName'=>$has_tags_val,
                        'IsActive'=>'1',
                        ]);
                    $has_tag_id=$hashTagData->id;
                    ContestHashTag::create([
                        'ContestID'=>$ContestId,
                        'HashTagID'=>$has_tag_id
                        ]);
                }
            }
        }
        return redirect()->route('admin.contests.list')->with('success','Contest created successfully');

    }
    public function edit($id){
        $ContestData = Contest::find($id);
        return view('admin.contests.edit',compact('ContestData'));
    }
    public function hastags(Request $request)
    {
        $get_all_hashtag=Hashtags::where('HashTagName', 'like', '%'.$request->q.'%')->get();
        $search_user_arr = array();
        if(!empty($get_all_hashtag))
        {
            foreach ($get_all_hashtag as $key => $user) {
                $search_user_arr[$key]['text'] = $user['HashTagName'];
                $search_user_arr[$key]['id'] = $user['Id'];
            }
        }
        return response()->json(['response'=>$search_user_arr]);
    }
    public function destroy(Request $request){
        $ContestData = Contest::find($request->id);
        if(file_exists(public_path().'/uploads/ContestReffrenceImage/'.$ContestData->ContestReffrenceImageUrl)){
            @unlink(public_path().'/uploads/ContestReffrenceImage/'.$ContestData->ContestReffrenceImageUrl);
        }
        ContestHashTag::where('ContestID',$request->id)->delete();
        Contest::where('id',$request->id)->delete();
        return response()->json(['succsess'=>true]);
    }
}

app/Http/Controllers/Api/ContestController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Carbon\Carbon;
use App\ContestModel;
use Str;

class ContestController extends Controller
{
    public function GetFreeContest(Request $request)
    {
        $userContest = $request->user()->FreeContest;
        if(!$userContest->isEmpty()){
        	return response()->json([
        	    'Success'=>true,
        	    'message' => 'Contest Found.',
        	    'data'=>$userContest
        	],201);
        }
        else{
        	return response()->json([
                'Success'=>false,
                'message' => 'Contest Not Found.'
            ], 401);
        }
    }
    public function GetPaidContest(Request $request)
    {
        $userContest = $request->user()->PaidContest;
        if(!$userContest->isEmpty()){
        	return response()->json([
        	    'Success'=>true,
        	    'message' => 'Contest Found.',
        	    'data'=>$userContest
        	],201);
        }
        else{
        	return response()->json([
                'Success'=>false,
                'message' => 'Contest Not Found.'
            ], 401);
        }
    }
}

resources/views/admin/contests/create.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop User
@endsection
@section('style')
    <!-- <link href="{{asset('assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet"> -->
    <link href="{{asset('assets/plugins/daterangepicker/daterangepicker.css')}}" rel="stylesheet">
    <link href="{{asset('assets/plugins/select2/dist/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{asset('assets/plugins/dropify/dist/css/dropify.min.css')}}">
<style type="text/css">
    .invalid-feedback{
        display: block;
        font-weight: bold;
    }
        .select2-container--default .select2-selection--multiple {
            border-top: none !important;
            border-left: none !important;
            border-right: none !important;
            border-bottom: 1px solid #d9d9d9 !important;
        }
        .select2-container--default.select2-container--focus .select2-selection--multiple{
            border-top: none !important;
            border-left: none !important;
            border-right: none !important;
            border-bottom: 1px solid #d9d9d9 !important;
        }
        .btn-circle.btn-lg{
            padding: 10px 15px !important;
        }
        .dropify-wrapper .dropify-message p {
            text-align: center !important;
        }
        .dropify-btn{
            margin-bottom: 20px;
        }
        .floating-labels .form-control:focus{
            border-bottom: 1px solid #d9d9d9 !important;
        }
        .container_box{
            border: 1px solid #80808061;
            padding: 20px;
            margin-bottom: 10px;
        }
        .clear-both{
            clear: both;
        }
</style>
@endsection
@section('content')

<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Edit User</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.users.list')}}">User</a></li>
                <li class="breadcrumb-item active">Edit User</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="floating-labels m-t-40" method="post" action="{{route('admin.contests.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group m-b-40">
                            <select class="form-control p-0" name="ContestType" id="ContestType">
                                <option value=" ">Please select Contests Type</option>
                                <option value="0" {{ (old('ContestType')=='0') ? 'selected' : '' }}>Audio</option>
                                <option value="1" {{ (old('ContestType')=='1') ? 'selected' : '' }}>Video</option>
                                <option value="2" {{ (old('ContestType')=='2') ? 'selected' : '' }}>Writing</option>
                            </select>
                            <span class="bar"></span>
                            <label for="ContestType">Contest Type</label>
                            @error('ContestType')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('ContestType') }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="ContestTitle" id="ContestTitle" data-toggle="tooltip" data-placement="bottom" title="Contest Title" value="{{ old('ContestTitle') }}">
                                <span class="bar"></span>
                                <label for="ContestTitle">Contest Title</label>
                                @error('ContestTitle')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('ContestTitle') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group m-b-40">
                                <select class="form-control p-0" name="RewardType" id="RewardType">
                                    <option value=" ">Please select Reward Type</option>
                                    <option value="0" {{ (old('ContestType')=='0') ? 'selected' : '' }}>Ruppies</option>
                                    <option value="1" {{ (old('ContestType')=='1') ? 'selected' : '' }}>Point</option>
                                </select>
                                <span class="bar"></span>
                                <label for="RewardType">Reward Type</label>
                                @error('RewardType')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('RewardType') }}</strong>
                                    </span>
                                @enderror
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="RewardPoints" id="RewardPoints" data-toggle="tooltip" data-placement="bottom" title="Reward Points" value="{{old('RewardPoints')}}">
                                <span class="bar"></span>
                                <label for="RewardPoints">Reward Points</label>
                                @error('RewardPoints')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('RewardPoints') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="PremiumRewardPoints" id="PremiumRewardPoints" data-toggle="tooltip" data-placement="bottom" title="Premium Reward Points" value="{{old('PremiumRewardPoints')}}">
                                <span class="bar"></span>
                                <label for="PremiumRewardPoints">Premium Reward Points</label>
                                @error('PremiumRewardPoints')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('PremiumRewardPoints') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="StartTime" id="StartTime" data-toggle="tooltip" data-placement="bottom" title="Contest Duration">
                                <span class="bar"></span>
                                <label for="StartTime">Contest Duration</label>
                                @error('StartTime')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('StartTime') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group m-b-40">
                            <select name="has_tags[]" id="has_tags" class="select2 m-b-10 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose">
                                </select>
                            <span class="bar"></span>
                            @error('has_tags')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('has_tags') }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title"></h4>
                                        <label for="ContestReffrenceImageUrl">Upload Image</label>
                                        <input type="file" id="ContestReffrenceImageUrl" name="ContestReffrenceImageUrl" class="dropify" />
                                    </div>
                                </div>
                                @error('ContestReffrenceImageUrl')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('ContestReffrenceImageUrl') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row m-b-40">
                            <div class="col-md-6">
                                <div class="demo-checkbox">
                                    <input type="checkbox" id="IsPaid" name="IsPaid" class="filled-in chk-col-light-blue">
                                    <label for="IsPaid">Is Paid</label>
                                    </div>
                            </div>
                        </div>
                        
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <button type="submit" class="btn btn-info waves-effect waves-light m-t-10"> <i class="fa fa-check"></i> Submit</button>
                                            <a href="{{route('admin.users.list')}}" class="btn btn-inverse m-t-10">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<!-- <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js">
    </script> -->

<script src="{{asset('assets/plugins/moment/moment.js')}}"></script>
<script src="{{asset('assets/plugins/daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('assets/plugins/select2/dist/js/select2.full.min.js')}}" type="text/javascript"></script>
<script type="text/javascript">
    $('#StartTime').daterangepicker({
        timePicker: true,
        timePicker24Hour: true,
        timePickerSeconds: true,
        timePickerIncrement: 3000,
        locale: {
                        format: 'YYYY-MM-DD HH:mm:ss'
        }
      });
$(function() {

    $(".select2").select2({
          placeholder: "Select Tags",
            tags: true,
            tokenSeparators: [",", " "],
            ajax:{
              url: "{{route('admin.contests.hastags')}}",
              headers: {'X-CSRF-Token': Laravel.csrfToken},
              dataType: 'json',
              type:"POST",
              data: function(term) {
                  return {
                    q:term.term,
                  };
              },
              processResults: function(data, page) {
                data=data.response;
                  return {
                      results: $.map(data, function(item) {
                          return {
                              text: item.text,
                              id: item.id,
                              isNew:true
                          }
                      })
                  };
              }
            }
        }).on("select2:select", function(e) {
        if(e.params.data.isNew){
            $('#console').append('<code>New tag: {"' + e.params.data.id + '":"' + e.params.data.text + '"}</code><br>');
            $(this).find('[value="'+e.params.data.id+'"]').replaceWith('<option selected value="'+e.params.data.id+'">'+e.params.data.text+'</option>');
        }
});
});
</script>
<script src="{{asset('assets/plugins/dropify/dist/js/dropify.min.js')}}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // Basic
        $('.dropify').dropify();
    });
</script>
@endsection

resources/views/admin/contests/index.blade.php
@extends('include.admin_app')
@section('metatitle')
    PopinLoop Role
@endsection
@section('content')
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Contests List</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">Contests List</li>
            </ol>
        </div>
        <div class="col-md-7 col-4 align-self-center">
            <div class="d-flex m-t-10 justify-content-end">
                <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                    @if(Auth::user()->can('add-contests'))
                        <a href="{{route('admin.contests.add')}}" class="btn btn-info waves-effect waves-light m-t-10 add-a-tag-color">Add Contest</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <!-- Column -->
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table striped m-b-20" id="editable-datatable">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th># OF Applied Person</th>
                                    @if(Auth::user()->can('edit-contests') || Auth::user()->can('delete-contests'))
                                    @php
                                        $is_role=true;
                                    @endphp
                                    <th>Action</th>
                                    @else
                                    @php
                                        $is_role=false;
                                    @endphp
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{asset('assets/plugins/jquery-datatables-editable/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/plugins/datatables/media/js/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/mindmup-editabletable.js')}}"></script>
<script src="{{asset('assets/plugins/tiny-editable/numeric-input-example.js')}}"></script>
@if(Session::has('success'))
    <script type="text/javascript">
        const Toast = Swal.mixin({
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 3000
        });
        Toast.fire({
          type: 'success',
          title: '{!! Session::get("success") !!}'
        });
    </script>
@endif
<script type="text/javascript">
    $(function() {
        var role = '{{$is_role}}';
        var table=$('#editable-datatable').DataTable({
           processing: true,
           serverSide: true,
           ajax:{
                headers: {'X-CSRF-Token': Laravel.csrfToken},
                url:'{!! route("admin.contests.data") !!}',
                type:'POST'
            },
           columns: [
                { data: 'Id', name: 'Id' },
                { data: 'ContestTitle', name: 'ContestTitle' },
                { data: 'contest_user_count', name: 'contest_user_count' },
                { data: 'action', name: 'action',visible : role }
            ]
        });
    });
    function delete_confirmation(ele,id){
        swal({   
            title: "Are you sure?",   
            text: "You won't be able to revert this!",   
            type: "warning",   
            showCancelButton: true,   
            confirmButtonColor: "#DD6B55",   
            confirmButtonText: "Yes, delete it!",   
            closeOnConfirm: false,
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    headers: {'X-CSRF-Token': Laravel.csrfToken},
                    url: '{{ route("admin.contests.destroy") }}',
                    dataType : 'json',
                    data: {id:id},
                    success: function(response) {
                        if(response.succsess == true){
                            Swal.fire(
                              'Deleted!',
                              'Your file has been deleted.',
                              'success'
                            );
                            $('#editable-datatable').DataTable().ajax.reload();
                            redrawDatatable();
                        }
                    },
                    error: function (jqXHR, status, exception) {
                        if (jqXHR.status === 0) {
                            error = 'Not connected.\nPlease verify your network connection.';
                        } else if (jqXHR.status == 404) {
                            error = 'The requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            error = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            error = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            error = 'Time out error.';
                        } else if (exception === 'abort') {
                            error = 'Ajax request aborted.';
                        } else {
                            error = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        Swal.fire('Error!',error,'error');
                    }
                });
            }
        });
    }
    function redrawDatatable(){
        $('#editable-datatable').DataTable().ajax.reload();
    }
</script>
@endsection